"""A recorded run of camera status samples, for the demo.

Run: python fixtures/generate_status_log.py

This is a FIXTURE. No Ring device was polled to produce it; the file it writes
says so in its own header field. It exists because coverage.py refuses to let a
"not consistent" verdict stand over a window this app cannot show the camera was
answering across, so a demo with no status samples can only ever reach
"indeterminate", which would hide the interesting branch rather than show it.

One deliberate outage is included: the camera stops answering between 10:00 and
11:15 on 20 September 2026. A claim landing in that hour demonstrates the rule
the whole module exists for, which is that an empty event log during an outage
is not a finding.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "device_status" / "front-door.json"
INTERVAL = dt.timedelta(minutes=15)

COVERED_RUNS = [
    # (day, first sample, last sample)
    ("2026-09-18", "12:00", "16:00"),
    ("2026-09-20", "07:00", "16:00"),
    ("2026-09-22", "09:00", "13:00"),
]
OUTAGE = ("2026-09-20", "10:00", "11:15")


def _stamps(day: str, start: str, end: str):
    begin = dt.datetime.fromisoformat(f"{day}T{start}:00+00:00")
    finish = dt.datetime.fromisoformat(f"{day}T{end}:00+00:00")
    cursor = begin
    while cursor <= finish:
        yield cursor
        cursor += INTERVAL


def main() -> None:
    outage_start = dt.datetime.fromisoformat(f"{OUTAGE[0]}T{OUTAGE[1]}:00+00:00")
    outage_end = dt.datetime.fromisoformat(f"{OUTAGE[0]}T{OUTAGE[2]}:00+00:00")
    samples = []
    for day, start, end in COVERED_RUNS:
        for stamp in _stamps(day, start, end):
            online = not (outage_start <= stamp <= outage_end)
            samples.append({"timestamp": stamp.isoformat(), "online": online})
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "fixture": True,
                "note": (
                    "Generated by fixtures/generate_status_log.py. No Ring device was polled to "
                    "produce this file. A live run would come from RingClient.get_device_status "
                    "through status_poller.poll_once."
                ),
                "device_id": "ava1.ring.device.FRONTDOOR",
                "interval_minutes": int(INTERVAL.total_seconds() // 60),
                "samples": samples,
            },
            indent=2,
        )
    )
    offline = sum(1 for s in samples if not s["online"])
    print(f"wrote {OUT} with {len(samples)} samples, {offline} of them offline")


if __name__ == "__main__":
    main()
