"""Sampling the camera's status, so the pack can say whether it was watching.

Ring publishes no "camera went offline" webhook. It publishes
``GET /v1/devices/{id}/status``, which ``RingClient.get_device_status`` calls.
This module is the scheduled caller: every ``INTERVAL`` it asks, and records the
answer as a sample. ``coverage.py`` turns a run of samples into the spans this
app can say the camera was answering across, and ``reconcile.py`` refuses to
reach a "not consistent" verdict over a span that is not one of them.

The poll loop is not run in this submission, because there is no live Ring
account to poll (README.md, "The honest boundary"). What runs instead is
``replay_log``, which reads a recorded run of samples out of
``fixtures/device_status/`` and puts them through the same ``record_sample``
path a live poll would. The recorded run is plainly a fixture, generated by
``fixtures/generate_status_log.py``, and it is labelled as one in the file it
writes.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

from .coverage import sample
from .ring_errors import RingAPIError

INTERVAL = dt.timedelta(minutes=15)


def read_status(client, device_id: str) -> bool:
    """One live poll. True when the device answered as online.

    A Ring API error is not an offline device: a 401 says this app's token is
    wrong, which is a fact about this app. It propagates rather than being
    recorded as a camera fault, because recording it as one would put a coverage
    gap on a user's evidence pack for a reason that has nothing to do with their
    camera.
    """
    status = client.get_device_status(device_id)
    attributes = status.get("attributes", status)
    return bool(attributes.get("online", attributes.get("connected", False)))


def record_sample(store, device_id: str, timestamp: dt.datetime, online: bool) -> None:
    store.add_event(sample(timestamp, online=online, device_id=device_id))


def poll_once(client, device_id: str, store, now: dt.datetime | None = None) -> bool:
    now = now or dt.datetime.now(dt.timezone.utc)
    try:
        online = read_status(client, device_id)
    except RingAPIError:
        raise
    record_sample(store, device_id, now, online)
    return online


def replay_log(path: Path, store) -> int:
    """Replay a recorded run of samples through the same path a live poll uses."""
    payload = json.loads(Path(path).read_text())
    for entry in payload["samples"]:
        record_sample(
            store,
            payload.get("device_id", "ava1.ring.device.FRONTDOOR"),
            dt.datetime.fromisoformat(entry["timestamp"]),
            bool(entry["online"]),
        )
    return len(payload["samples"])
